require("user.user-commands")

require("user.plugins")
require("user.options")
require("user.keymaps")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.toggleterm")
require("user.lualine")
require("Comment").setup()
require("user.context")
require("user.treesitter")
require("user.clipboard")
require("user.folding")
require("user.colorscheme")
require("user.templates")
require("user.code-forces")
-- require("luasnip.loaders.from_snipmate").lazy_load({paths = "./snippets"})
require("user.conda-envs")
require("user.recent-dir")
require("user.aerial")
