require("user.user-commands")

require("user.colorscheme")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.gitsigns")
require("user.nvim-tree")
require("nvim-tree").setup({})
require("user.bufferline")
require("user.toggleterm")
require("user.lualine")
require("Comment").setup()
require("user.context")
require("user.treesitter")
require("user.clipboard")

