require("user.options")
require("user.keymaps")
require("user.lazy")
require("user.clipboard")
require("user.colorscheme")


-- require("user.lsp")
-- require("Comment").setup()
-- require("user.context")
-- require("user.folding")
require("user.templates")
require("user.code-forces")
require("user.conda-envs")
-- require("user.recent-dir")
-- require("user.aerial")
-- require("user.ale")
-- require("user.lsp_signature")
-- require("user.highlight")
require("user.large-file-warning")



-- require("user.cmp")
-- require("user.treesitter")
-- require("user.lualine")
-- require("user.nvim-tree")
-- require("user.telescope")
-- require("user.colorscheme")
-- require("user.gitsigns")
