DOTFILES_MACHINE_NAME="${DOTFILES_MACHINE_NAME:-$DOTFILES_MACHINE_PROFILE}"
ZSH_THEME="${ZSH_THEME:-gnzh}"
EDITOR="${EDITOR:-nvim}"
VISUAL="${VISUAL:-$EDITOR}"
FZF_SHELL_ZSH="${FZF_SHELL_ZSH:-$HOME/.fzf.zsh}"
FZF_SHELL_BASH="${FZF_SHELL_BASH:-$HOME/.fzf.bash}"

export DOTFILES_MACHINE_NAME ZSH_THEME EDITOR VISUAL
export FZF_SHELL_ZSH FZF_SHELL_BASH
