DOTFILES_MACHINE_NAME="mlsys-b200"
CACHE_ROOT="/raid/d1su/cache"
DATA_ROOT="/raid"
HF_HOME="/raid/huggingface"
ALTERNATE_NVIM_BIN="$DOTFILES_DIR/nvim-linux-x86_64.appimage"
NVM_DIR="$HOME/.nvm"
DOTFILES_BASH_EXEC_ZSH=1

export DOTFILES_MACHINE_NAME CACHE_ROOT DATA_ROOT HF_HOME NVM_DIR
export DOTFILES_BASH_EXEC_ZSH
export ALTERNATE_NVIM_BIN
